version: '2'
services:
  ecs:
    container_name: ecs-agent
    image: amazon/amazon-ecs-agent:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/log/ecs/:/log"
      - "/data:/data"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "/var/run/docker/execdriver/native:/var/lib/docker/execdriver/native:ro"
    ports:
      - 51678-51679:51678-51679
    environment:
      INSTANCE_IP: 127.0.0.1
      ECS_LOGFILE: /log/ecs-agent.log
      ECS_LOGLEVEL: info
      ECS_DATADIR: /data
      ECS_CLUSTER: local_test
      ECS_AVAILABLE_LOGGING_DRIVERS: '["json-file","syslog","journald","gelf","fluentd","awslogs"]'
      ECS_ENABLE_TASK_IAM_ROLE: "true"
